#!/bin/sh
#
#
#
#   Startup/shutdown script for running Tomcat/Fedora v1.1.
#
#   Linux chkconfig stuff:
#
#   chkconfig: 2345 70 10
#   description: Startup/shutdown script for running Tomcat/Fedora.
#
# Source function library.
if [ -f /etc/init.d/functions]; then
     . /etc/init.d/functions
fi

PROG=Fedora

# *** Please make sure you change the fedora user to reflect the local setup. ***

FEDORA_USER=fedora

start () {
	echo -n $"Starting $PROG: "
	# check to see if the process is already running
	if [ -f /var/lock/fedora ]; then
		echo "$PROG is already running"
				
	else
		# start Tomcat/Fedora as the fedora user
		su - $FEDORA_USER -c /usr/local/fedora/tomcat/bin/startup.sh &>/dev/null
       		sleep 3
		ps -ef | grep 'tomcat' | grep -v 'grep' &>/dev/null
		RETVAL=$?
		if [ $RETVAL = 0 ]; then
			touch /var/lock/fedora
			echo -e "                                          [ \033[0;32m OK\033[0;39m""  ]"
		else
			echo -e "                                          [ \033[0;31m FAILED\033[0;39m""  ]"
		fi
	fi
}

stop () {
	# stop daemon
	echo -n $"Stopping $PROG: "
	# check to see if the process is running
	if [ ! -f /var/lock/fedora ]; then
		echo "$PROG is not running"
	else
		# use the fedora shutdown script to stop Tomcat/Fedora. Doesn't seem to shut down properly so issue the command twice.
		su - $FEDORA_USER -c /usr/local/fedora/tomcat/bin/shutdown.sh &>/dev/null
		sleep 2
		su - $FEDORA_USER -c /usr/local/fedora/tomcat/bin/shutdown.sh &>/dev/null 
		RETVAL=$?
		echo -e "                                          [ \033[0;32m OK\033[0;39m""  ]"
		[ $RETVAL = 0 ] && rm -f /var/lock/fedora
	fi
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	status)
		if [ -f /var/lock/fedora ]; then
			echo "$PROG (pid `ps -ef | grep 'tomcat' | grep -v 'grep' | awk '{print $2}'`) is running..."
		else
			echo "$PROG has not been started."
		fi
	;;
	*)

	echo $"Usage: $PROG {start|stop|restart|status}"
	exit 3
esac

exit $RETVAL

