#!/bin/sh
# 
# Created by: Steve Young
# Hamilton College
# November 2011

# chkconfig: 35 95 05
# description: Fedora Commons with Islandora

. /opt/islandora/etc/env.sh

# the following is needed to make Dkjota start up properly
cd $CATALINA_HOME/logs
export PWD=$CATALINA_HOME/logs


case $1 in
'start')
	echo -n $"Starting Fedora as user $FEDORA_USER: "
        su - -c $FEDORA_START $FEDORA_USER > /dev/null
        echo "     Done"
        ;;
'stop')
        echo -n $"Shutting down Fedora: "
        su - -c $FEDORA_STOP $FEDORA_USER > /dev/null
        echo "     Done"
        ;;
'restart')
	echo -n $"Shutting down Fedora: "
        su - -c $FEDORA_STOP $FEDORA_USER > /dev/null
        echo "     Done"
	sleep 10
	echo -n $"Starting Fedora as user $FEDORA_USER: "
        su - -c $FEDORA_START $FEDORA_USER > /dev/null
        echo "     Done"
	;;
*)
	echo "usage: `basename $0` {start|stop|restart}"
        ;;
esac
